name: auto-pr
on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - "*"

jobs:
  pull_request:
    if: github.ref != 'refs/heads/main'
    uses: innago-property-management/Oui-DELIVER/.github/workflows/auto-pr.yml@main
    secrets:
      token: ${{ secrets.SEMVER_TOKEN }}
